/** Stable brand icon keys for about / stack surfaces. */
export type StackIconId =
  | "typescript"
  | "nextdotjs"
  | "react"
  | "expo"
  | "tailwindcss"
  | "turborepo"
  | "nestjs"
  | "mongodb"
  | "firebase"
  | "googlecloud"
  | "cloudflare"
  | "hono"
  | "postgresql"
  | "prisma"
  | "solidity"
  | "sanity"
  | "github"
  | "cursor"
  | "claudecode"
  | "claude"
  | "playwright"
  | "finance";
